swagger: '2.0'
info:
  description: This is the merchant API
  version: 1.0.0
  title: Merchant API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Merchant Profile
    description: Merchant profile
  - name: Store Group
    description: Store Group
  - name: Store
    description: Store
  - name: Merchant Request
    description: Merchant request
schemes:
  - https
  - http
paths:
  '/merchants/{merchantId}':
    get:
      tags:
        - Merchant Profile
      summary: Get merchant profile
      operationId: findMerchantById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Merchant'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - read
  '/merchants':
    post:
      tags:
        - Merchant Profile
      summary: Create a new merchant profile
      operationId: createMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: body
          in: body
          description: New merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/merchants ':
    put:
      tags:
        - Merchant Profile
      summary: Update merchant profile
      operationId: updateMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: body
          in: body
          description: Update merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/merchants/{merchantId}/groups':
    get:
      tags:
        - Store Group
      summary: Get store group
      operationId: findStoreGroupById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
        - name: groupId
          in: path
          description: Store group Id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreGroup'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - read
  '/merchants/{merchantId}/stores':
    get:
      tags:
        - Store
      summary: Get stores
      operationId: findStores
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
        - name: site
          in: query
          description: Site
          required: false
          type: string
        - name: groupId
          in: query
          description: Store group Id
          required: false
          type: string
        - name: text
          in: query
          description: search criteria which query from storeCode and storeName
          required: false
          type: string
        - name: active
          in: query
          description: store active status
          required: false
          type: boolean
        - name: page
          in: query
          description: Page number
          required: false
          type: integer
        - name: size
          in: query
          description: number record per one page
          required: false
          type: integer   
        - name: sortBy
          in: query
          description: field name for sorting
          required: false
          type: string
        - name: sortOrder
          in: query
          description: sorting direction ('desc','asc')
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreListPagination'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  '/merchants/requests/validateTaxId':
    get:
      tags:
        - MerchantRequest
      summary: Validate taxId
      operationId: validateTaxId
      consumes:
        - application/json
      produces:
        - application/json  
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: taxId
          in: query
          description: taxId
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: |
            Bad request
              code: "01001"
              message: "Tax ID/ ID card is duplicated {taxId}"
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  '/merchants/requests/save':
    put:
      tags:
        - MerchantRequest
      summary: Save merchant request
      operationId: saveMerchantRequest
      consumes:
        - application/json
      produces:
        - application/json  
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Merchantrequest payload
          required: true
          schema:
            $ref: '#/definitions/MerchantRequest'
      responses:
        '200':
          description: successful operation
        '400':
          description: |
            Bad request
              Example: Error saving merchant request, Error creating merchant request, Error updating merchant request
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant Request not found
      security:
        - oAuth2:
            - write
    
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Merchant:
    type: object
    description: Merchant
    properties:
      id:
        type: string
      version:
        type: string
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      sites:
        type: array
        items:
          $ref: '#/definitions/Site'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Site:
    type: object
    description: Site
    properties:
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
  StoreGroup:
    type: object
    description: Store Group
    properties:
      id:
        type: string
      version:
        type: string
      merchant:
        type: string
      site:
        type: string
      parent:
        type: string
      predecessors:
        type: array
        items:
          type: string
      stores:
        type: array
        items:
          $ref: '#/definitions/StoreList'
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Contact:
    type: object
    description: Contact
    properties:
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
  Policy:
    type: object
    description: Policy
    properties:
      currency:
        type: string
      language:
        type: string
      timezone:
        type: string
      country:
        type: string
      openTime:
        type: string
      closeTime:
        type: string
  StoreListPagination:
    type: object
    description: Store list page
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/StoreList'
  Pagination:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  StoreList:
    type: object
    description: Store list
    properties:
      merchant:
        type: string
      site:
        type: string
      group:
        type: string
      store:
        type: string
      number:
        type: string
      name:
        type: string
      active:
        type: boolean
      deleted:
        type: boolean
  MerchantRequest:
    type: object
    description: Merchant request
    properties:
      id:
        type: string
      version:
        type: integer
        format: int64
      requestNo:
        type: string
      type:
        $ref: '#/definitions/ChangeRequestType'
      status:
        $ref: '#/definitions/ChangeRequestStatus'
      step:
        $ref: '#/definitions/MerchantRequestStep'
      merchantInfo:
        $ref: '#/definitions/MerchantInfo'
      legalDocument:
        $ref: '#/definitions/LegalDocument'
      orderPolicy:
        $ref: '#/definitions/OrderPolicy'
      createDate:
        type: string
      createdBy:
        type: string
      createdByName:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
      lastModifiedByName:
        type: string
  MerchantInfo:
    type: object
    description: Merchant info
    properties:
      merchantProfile:
        $ref: '#/definitions/MerchantProfile'
      ownerProfile:
        $ref: '#/definitions/OwnerProfile'
      storeProfile:
        type: array
        items:
          $ref: '#/definitions/StoreProfile'
      
  LegalDocument:
    type: object
    description: Legal document
    properties:
      idCard: 
        type: string
      houseRegistration:
        type: string
      letterOfIntent:
        type: string
      contractSignOff:
        type: string
  OrderPolicy:
    type: object
    description: Order policy
    properties:
      minOrder:
        type: number
      orderSchedule:
        type: array
        items:
          type: string
      deliverySchedule:
        type: array
        items:
          type: string
  MerchantProfile:
    type: object
    description: Merchent profile
    properties:
      customerType:
        type: string
      taxId:
        type: string
      merchanType:
        type: string
      merchantName:
        type: string
      address:
        type: string
      state:
        type: string
      region:
        type: string
      postCode:
        type: string
      country:
        type: string
      currency:
        type: string
  OwnerProfile:
    type: object
    description: Owner profile
    properties:
      contactFirstname:
        type: string
      contactLastName:
        type: string
      contactLocalFirstname:
        type: string
      contactLacalLastName:
        type: string
      countryCode:
        type: string
      mobilePhone:
        type: string
      email:
        type: string
      gender:
        type: string
      birthDate:
        type: string
      testScore:
        type: string
      attitudeTest:
        type: string
  StoreProfile:
    type: object
    description: Store profile
    properties:
      storeCode:
        type: string
      storeName:
        type: string
      taxNo:
        type: string
      branchNo:
        type: string
      address:
        type: string
      state:
        type: string
      region:
        type: string
      postCode:
        type: string
      country:
        type: string
      timezone:
        type: string 
      phone:
        type: string
      buildingType:
        type: string
      noOfUnit:
        type: string
      propertyW:
        type: string
      propertyL:
        type: string
      propertyH:
        type: string
      propertyOwnership:
        type: string
      rentalFee:
        type: object
        properties:
          amount: 
            type: number
          currency: 
            type: string
      saleSpace:
        type: number
      stockSpace:
        type: number
      parking:
        type: string
      lattitude:
        type: number
      longitude:
        type: number
      areaType:
        type: string
      poiType:
        type: string
      storeFrontPicture:
        type: array
        items:
          type: string
      storeFrontVideo:
        type: string
  ChangeRequestType:
    type: string
    enum:
      - N
      - E
    description: |
      Type:
        * `E` - Edit
        * `N` - New
  ChangeRequestStatus:
    type: string
    enum:
      - D
      - WV
      - WS
      - WA
      - C
      - R
    description: |
      Status:
        * `D`  - Draft
        * `WV` - Awaiting Verify
        * `WS` - Awaiting Submit
        * `WA` - Awaiting Approval
        * `C`  - Complete
        * `R`  - Rejected
  MerchantRequestStep:
    type: string
    enum:
      - P
      - L
      - O
      - F
    description: |
      Step:
        * `P` - Profile
        * `L` - Legal Document
        * `O` - Order Policy
        * `F` - First Lot
