swagger: '2.0'
info:
  description: This is the merchant API
  version: 1.0.0
  title: Merchant API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Merchant Profile
    description: Merchant profile
  - name: Store Country
    description: Store Country
  - name: Store Group
    description: Store Group
schemes:
  - https
  - http
paths:
  '/merchants/{merchantId}':
    get:
      tags:
        - Merchant Profile
      summary: Get merchant profile
      operationId: findMerchantById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Merchant'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - read
  '/merchants':
    post:
      tags:
        - Merchant Profile
      summary: Create a new merchant profile
      operationId: createMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/merchants ':
    put:
      tags:
        - Merchant Profile
      summary: Update merchant profile
      operationId: updateMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/storeCountries/{storeCountryId}':
    get:
      tags:
        - Store Country
      summary: Get store country
      operationId: findStoreCountryById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: storeCountryId
          in: path
          description: Store country id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreCountry'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store country not found
      security:
        - oAuth2:
            - read
  '/storeCountries':
    post:
      tags:
        - Store Country
      summary: Create a new store country
      operationId: createStoreCountry
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New store country payload
          required: true
          schema:
            $ref: '#/definitions/StoreCountry'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store country not found
      security:
        - oAuth2:
            - write
  '/storeCountries ':
    put:
      tags:
        - Store Country
      summary: Update store country
      operationId: updateStoreCountry
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update store country payload
          required: true
          schema:
            $ref: '#/definitions/StoreCountry'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store country not found
      security:
        - oAuth2:
            - write
  '/storeGroups/{storeGroupId}':
    get:
      tags:
        - Store Group
      summary: Get store group
      operationId: findStoreGroupById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: storeGroupId
          in: path
          description: Store group id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreGroup'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - read
  '/storeGroups':
    post:
      tags:
        - Store Group
      summary: Create a new store group
      operationId: createStoreGroup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New store group payload
          required: true
          schema:
            $ref: '#/definitions/StoreGroup'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - write
  '/storeGroups ':
    put:
      tags:
        - Store Group
      summary: Update store group
      operationId: updateStoreGroup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update store group payload
          required: true
          schema:
            $ref: '#/definitions/StoreGroup'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - write
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Merchant:
    type: object
    description: Merchant
    properties:
      id:
        type: string
      version:
        type: string
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  StoreCountry:
    type: object
    description: Store Country
    properties:
      id:
        type: string
      version:
        type: string
      merchant:
        type: string
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  StoreGroup:
    type: object
    description: Store Group
    properties:
      id:
        type: string
      version:
        type: string
      merchant:
        type: string
      storeCountry:
        type: string
      parent:
        type: string
      hierarchy:
        type: array
        items:
          type: string
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Contact:
    type: object
    description: Contact
    properties:
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
  Policy:
    type: object
    description: Policy
    properties:
      currency:
        type: string
      language:
        type: string
      timezone:
        type: string
      country:
        type: string
      openTime:
        type: string
      closeTime:
        type: string