swagger: '2.0'
info:
  description: This is the merchant API
  version: 1.0.0
  title: Merchant API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Merchant Profile
    description: Merchant profile
  - name: Store Group
    description: Store Group
  - name: Store
    description: Store
schemes:
  - https
  - http
paths:
  '/merchants/{merchantId}':
    get:
      tags:
        - Merchant Profile
      summary: Get merchant profile
      operationId: findMerchantById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Merchant'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - read
  '/merchants':
    post:
      tags:
        - Merchant Profile
      summary: Create a new merchant profile
      operationId: createMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/merchants ':
    put:
      tags:
        - Merchant Profile
      summary: Update merchant profile
      operationId: updateMerchant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update merchant payload
          required: true
          schema:
            $ref: '#/definitions/Merchant'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Merchant not found
      security:
        - oAuth2:
            - write
  '/merchants/{merchantId}/groups/{groupId}':
    get:
      tags:
        - Store Group
      summary: Get store group by Id
      operationId: findStoreGroupById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant id
          required: true
          type: string
        - name: groupId
          in: path
          description: Store group Id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreGroup'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - read
  '/merchants/{merchantId}/groups':
    post:
      tags:
        - Store Group
      summary: Create a new store group
      operationId: createStoreGroup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
        - name: body
          in: body
          description: New store group payload
          required: true
          schema:
            $ref: '#/definitions/StoreGroup'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - write
  '/merchants/{merchantId}/groups':
    put:
      tags:
        - Store Group
      summary: Update store group
      operationId: updateStoreGroup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
        - name: body
          in: body
          description: Update store group payload
          required: true
          schema:
            $ref: '#/definitions/StoreGroup'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store group not found
      security:
        - oAuth2:
            - write
  '/merchants/{merchantId}/stores':
    get:
      tags:
        - Store
      summary: Get stores
      operationId: findStores
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "merchant.api.tdshop.io"
          required: true
          type: string
        - name: merchantId
          in: path
          description: Merchant Id
          required: true
          type: string
        - name: site
          in: query
          description: Site
          required: false
          type: string
        - name: groupId
          in: query
          description: Store group Id
          required: false
          type: string
        - name: text
          in: query
          description: search criteria which query from storeCode and storeName
          required: false
          type: string
        - name: active
          in: query
          description: store active status
          required: false
          type: boolean
        - name: page
          in: query
          description: Page number
          required: false
          type: integer
        - name: size
          in: query
          description: number record per one page
          required: false
          type: integer   
        - name: sortBy
          in: query
          description: field name for sorting
          required: false
          type: string
        - name: sortOrder
          in: query
          description: sorting direction ('desc','asc')
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreListPage'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Merchant:
    type: object
    description: Merchant
    properties:
      id:
        type: string
      version:
        type: string
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      sites:
        type: array
          items:
            $ref: '#/definitions/Site'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Site:
    type: object
    description: Site
    properties:
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
  StoreGroup:
    type: object
    description: Store Group
    properties:
      id:
        type: string
      version:
        type: string
      merchant:
        type: string
      site:
        type: string
      parent:
        type: string
      predecessors:
        type: array
        items:
          type: string
      stores:
        type: array
          items:
            $ref: '#/definitions/StoreList'
      code:
        type: string
      name:
        type: string
      contact:
        $ref: '#/definitions/Contact'
      policy:
        $ref: '#/definitions/Policy'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Contact:
    type: object
    description: Contact
    properties:
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
  Policy:
    type: object
    description: Policy
    properties:
      currency:
        type: string
      language:
        type: string
      timezone:
        type: string
      country:
        type: string
      openTime:
        type: string
      closeTime:
        type: string
  StoreListPage:
    type: object
    description: Store list page
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/StoreList'
  Page:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  StoreList:
    type: object
    description: Store list
    properties:
      merchant:
        type: string
      site:
        type: string
      group:
        type: string
      store:
        type: string
      number:
        type: string
      name:
        type: string
      active:
        type: boolean
      deleted:
        type: boolean
