swagger: '2.0'
info:
  description: This is the order API
  version: 1.0.0
  title: Order API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Cart
    description: Cart Profile
  - name: Order
    description: Order Profile
schemes:
  - https
  - http
paths:
  '/carts/{storeId}':
    get:
      tags:
        - Cart
      summary: Get Cart profile
      operationId: findCartByStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: storeId
          in: path
          description: Store id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cart'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - read
  '/carts/{storeId}/summary':
    get:
      tags:
        - Cart
      summary: Get Cart summary
      operationId: getCartSummary
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: storeId
          in: path
          description: Store id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              numberOfItems:
                type: integer
              amount:
                type: number
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - read    
  '/carts/{storeId} ':
    post:
      tags: 
        - Cart
      summary: Create Cart
      operationId: createCart
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: storeId
          in: path
          description: Store id
          required: true
          type: string
        - name: body
          in: body
          description: New cart payload
          required: true
          schema:
            $ref: '#/definitions/Cart'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/addItem':
    put:
      tags:
        - Cart
      summary: addItem
      operationId: addItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: x-user-id
          in: header
          description: user id
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "*:*:*:*"
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
        - name: body
          in: body
          description: New cart payload
          required: true
          schema:
            type: object
            properties:
              version:
                type: integer
                format: int64
              barcode:
                type: string
              qty:
                type: integer
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/updateItem':
    put:
      tags:
        - Cart
      summary: updateItem
      operationId: updateItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:  
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: x-user-id
          in: header
          description: user id
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
        - name: body
          in: body
          description: New cart payload
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
              version:
                type: integer
                format: int64
              barcode:
                type: string
              qty:
                type: integer
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/{barcode}':
    put:
      tags:
        - Cart
      summary: deleteItem
      operationId: deleteItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:  
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
        - name: barcode
          in: path
          description: Barcode id
          required: true
          type: string
        - name: x-user-id
          in: header
          description: User id
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Cart not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/deleteInvalidItems':
    put:
      tags:
        - Cart
      summary: deleteAllInvalidItems
      operationId: deleteInvalidItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:  
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
        - name: x-user-id
          in: header
          description: User id
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Cart not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/empty':
    put:
      tags:
        - Cart
      summary: empty cart
      operationId: emptyCart
      consumes:
        - application/json
      produces:
        - application/json
      parameters:  
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/carts/{cartId}/saveNote':
    put:
      tags:
        - Cart
      summary: save note
      operationId: saveNote
      consumes:
        - application/json
      produces:
        - application/json
      parameters:  
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: cartId
          in: path
          description: Cart id
          required: true
          type: string
        - name: body
          in: body
          description: note in cart
          required: true
          schema:
            type: object
            properties:
              additionalNote:
                type: string
      responses:
        '200':
          description: OK
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/orders/{orderNo}':
    get:
      tags:
        - Order
      summary: Get order
      operationId: findByNo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: orderNo
          in: path
          description: Order number
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Order not found
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Cart:
    type: object
    description: Cart
    required:
      - status
      - merchant
      - store
      - items
      - amount
    
    properties:
      id:
        type: string
      version:
        type: integer
        format: int64
      status:
        type: string
      merchant:
        type: string
      store:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/Item'
      amount:
        type: number
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Item:
    type: object
    description: Item
    required:
      - barcode
      - articleNo
      - productName
      - catalogLV1
      - catalogLV2
      - wholesalePrice
      - retailPrice
      - unit
      - unitFactor
      - qty
      - amount
      - remainingStock
      - averageSell
    properties:
      barcode:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      catalogLV1:
        type: string
      catalogLV2:
        type: string
      wholesalePrice:
        type: number
      retailPrice:
        type: number
      unit:
        type: string
      unitFactor:
        type: integer
      qty:
        type: integer
      amount:
        type: number
      remainingStock:
        type: integer
      averageSell:
        type: number
      productImageName:
        type: string
  CartStatusType:
    type: object
    description: CartStatusType
    properties:
      name:
        type: string
        enum:
        - INITIAL
        - MODIFIED
  Order:
    type: object
    description: Order
    required:
    - orderNo
    - status
    - merchant
    - store
    - billTo
    - shipTo
    - items
    - vat
    - amount
    
    properties:
      id:
        type: string
      version:
        type: integer
        format: int64
      orderNo:
        type: string
      status:
        type: string
      merchant:
        type: string
      store:
        type: string
      billTo:
        $ref: '#/definitions/BillTo'
      shipTo:
        $ref: '#/definitions/ShipTo'
      items:
        type: array
        items:
          $ref: '#/definitions/Order.Item'
      vat:
        type: number
      amount:
        type: number
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Order.Item:
    type: object
    description: Order.Item
    properties:
      barcode:
        type: string
      qty:
        type: integer
      amount:
        type: number
  BillTo:
    type: object
    description: BillTo
    properties:
      name:
        type: string
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
  ShipTo:
    type: object
    description: ShipTo
    properties:
      name:
        type: string
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
        