swagger: '2.0'
info:
  description: This is the order API
  version: 1.0.0
  title: Order API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Order
    description: Order
schemes:
  - https
  - http
paths:
  '/orders/{orderNo}':
    get:
      tags:
        - Order
      summary: Get oreder
      operationId: findByNo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "order.api.tdshop.io"
          required: true
          type: string
        - name: orderNo
          in: path
          description: Order number
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Order not found
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Order:
    type: object
    description: Order
    properties:
      id:
        type: integer
        format: int64
      number:
        type: string