swagger: '2.0'
info:
  description: This is the product API
  version: 1.0.0
  title: Product API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: TD Product Profile
    description: TD Product Profile
schemes:
  - https
  - http
paths:
  '/tdproducts/{productId}':
    get:
      tags:
        - TD Product Profile
      summary: Get TD product profile
      operationId: findTDProductById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: productId
          in: path
          description: Product id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TDProduct'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Product not found
      security:
        - oAuth2:
            - read
    delete:
      tags:
        - TD Product Profile
      summary: Delete TD product profile
      operationId: deleteTDProductById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: productId
          in: path
          description: Product id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
  /tdproducts:
    post:
      tags:
        - TD Product Profile
      summary: Create a new TD product profile
      operationId: createTDProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New product payload
          required: true
          schema:
            $ref: '#/definitions/TDProduct'
      responses:
        '201':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '409':
          description: Duplicate article number or barcode
        '422':
          description: Validation failed or malformed request
      security:
        - oAuth2:
            - write
    put:
      tags:
        - TD Product Profile
      summary: Update TD product profile
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update product payload
          required: true
          schema:
            $ref: '#/definitions/TDProduct'
      responses:
        '200':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
  '/tdproducts/requests':
    get:
      tags:
        - TD Product Request Profile
      summary: Get TD product request
      operationId: findTDProductRequestsByCriteria
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TDProductRequestPagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  /cjproducts:
    get:
      tags:
        - CJ Product Profile
      summary: Get CJ product list
      operationId: getCJProducts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search criteria on "Product Name" or "Article No" (Default "")
          required: false
          type: string
        - name: beginImportDate
          in: query
          description: Filter greater than or equal importDate
          required: false
          type: string
        - name: endImportDate
          in: query
          description: Filter less than or equal importDate
          required: false
          type: string
        - name: selectedStatus
          in: query
          description: Filter selected status ('S' - Used, 'U' - Not Used, 'N' - New)
          required: false
          type: string
        - name: type
          in: query
          description: Filter type (TD or CJ)
          required: false
          type: string
        - name: page
          in: query
          description: Number of page (Default 0)
          required: false
          type: integer
        - name: size
          in: query
          description: Size per page (Default 20)
          required: false
          type: integer
        - name: sortOrder
          in: query
          description: asc or desc
          required: false
          type: string
        - name: sortBy
          in: query
          description: Field name eg. productName, articleNo
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CJProductPagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  /cjproducts/select:
    post:
      tags:
        - CJ Product Profile
      summary: Update CJ product select status
      operationId: selectCJProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update CJ product select status payload
          required: true
          schema:
            $ref: '#/definitions/SelectCJProduct'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SelectCJProductResponse'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
      security:
        - oAuth2:
            - write
  /cjproducts/{articleNo}:
    get:
      tags:
        - CJ Product Profile
      summary: Get CJ product by using article no.
      operationId: getCJProductByArticleNo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: articleNo
          in: path
          description: Product Article No.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CJProductDto'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  TDProduct:
    type: object
    description: TD Product
    allOf: 
      - $ref: '#/definitions/Product'
      - type: object
        properties:
          productNameCJ:
            type: string
          size:
            type: string
          uom:
            type: string
          brand:
            type: string
          productDescription:
            type: string
          calVat:
            type: boolean
          restricted:
            type: boolean
          barcodes:
            type: array
            items:
              $ref: '#/definitions/TDBarcode'
  TDProductRequest:
    type: object
    description: TD Product Request
    properties:
      requestNo:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      requestType:
        type: string
      requestBy:
        type: string
      requestDate:
        type: string
      status:
        type: string
  TDProductRequestPagination:
    type: object
    description: Pagination object for TDProductRequest
    allOf: 
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/TDProductRequest'
  TDBarcode:
    type: object
    description: TD Barcode
    allOf: 
      - $ref: '#/definitions/Barcode'
      - type: object
        properties:
          status:
            type: string
          priceConfigs:
            type: array
            items:
              $ref: '#/definitions/PriceConfig'
  PriceConfig:
    type: object
    description: PriceConfig
    properties:
      retailPrice:
        type: number
        format: double
      wholesalePrice:
        type: number
        format: double
      effectiveDate:
        type: string
      endDate:
        type: string
  Pagination:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  CJProductPagination:
    allOf: 
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/CJProduct'
  CJProduct:
    type: object
    description: CJ Product
    allOf: 
      - $ref: '#/definitions/Product'
      - type: object
        properties:
          source:
            type: string
          supplier:
            type: string
          statusTD:
            type: string
          statusCJ:
            type: string
          isCalVat:
            type: boolean
          isControlSpecial:
            type: boolean
  CJProductDto:
    allOf: 
      - $ref: '#/definitions/CJProduct'
      - type: object
        properties:
          cjBarcodes:
            type: array
            items:
              $ref: '#/definitions/CJBarcode'
  CJBarcode:
    type: object
    description: CJ Barcode
    allOf: 
      - $ref: '#/definitions/Barcode'
      - type: object
        properties:
          retailPrice:
            type: number
            format: double
          cost:
            type: number
            format: double
          wholesalePrice:
            type: number
            format: double
          active:
            type: boolean
  SelectCJProduct:
    type: object
    description: Update CJ product select status
    properties:
      status:
        type: string
        enum:
          - S
          - U
          - 'N'
        description: |
          Status:
           * `S` - Select
           * `U` - Unused
           * `N` - New
      articleNos:
        type: array
        items:
          type: string
  SelectCJProductResponse:
    type: object
    description: Response of update CJ product select status
    properties:
      success:
        type: array
        items:
          type: string
      failure:
        type: array
        items:
          type: string
  Barcode:
    type: object
    description: Base barcode object for CJ and TD
    properties:
      id:
        type: string
      version:
        type: string
      barcode:
        type: string
      articleNo:
        type: string
      unit:
        type: string
      unitFactor:
        type: number
      barSize:
        type: string
      pkgLength:
        type: number
        format: double
      pkgWidth:
        type: number
        format: double
      pkgHeight:
        type: number
        format: double
      pkgWeight:
        type: number
        format: double
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Product:
    type: object
    description: Base product object for CJ and TD
    properties:
      id:
        type: string
      version:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      classCode:
        type: string
      className:
        type: string
      oem:
        type: string
      source:
        type: string
      shelfLife:
        type: integer
      location:
        type: string
      active:
        type: boolean
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  
