swagger: '2.0'
info:
  description: This is the product API
  version: 1.0.0
  title: Product API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: TD Product Profile
    description: TD Product Profile
schemes:
  - https
  - http
paths:
  '/tdproducts/{productId}':
    get:
      tags:
        - TD Product Profile
      summary: Get TD product profile
      operationId: findTDProductById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: productId
          in: path
          description: Product id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TDProduct'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Product not found
      security:
        - oAuth2:
            - read
    delete:
      tags:
        - TD Product Profile
      summary: Delete TD product profile
      operationId: deleteTDProductById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: productId
          in: path
          description: Product id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
  /tdproducts:
    post:
      tags:
        - TD Product Profile
      summary: Create a new TD product profile
      operationId: createTDProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New product payload
          required: true
          schema:
            $ref: '#/definitions/TDProduct'
      responses:
        '201':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '409':
          description: Duplicate article number or barcode
        '422':
          description: Validation failed or malformed request
      security:
        - oAuth2:
            - write
    put:
      tags:
        - TD Product Profile
      summary: Update TD product profile
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Update product payload
          required: true
          schema:
            $ref: '#/definitions/TDProduct'
      responses:
        '200':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
  '/cjproducts':
    get:
      tags:
        - CJ Product Profile
      summary: Get CJ product list
      operationId: getCJProducts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search criteria on "Product Name" or "Article No" (Default "")
          required: false
          type: string
        - name: statusCJ
          in: query
          description: Filter by CJ status (Default "A")
          required: false
          type: string
        - name: page
          in: query
          description: Number of page (Default 0)
          required: false
          type: integer
        - name: size
          in: query
          description: Size per page (Default 20)
          required: false
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Pagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Product not found
      security:
        - oAuth2:
            - write
  '/cjproducts/status':
    patch:
      tags:
        - CJ Product Profile
      summary: Change CJ product status
      operationId: changeCJProductStatus
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "product.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Change CJ product status payload
          required: true
          schema:
            $ref: '#/definitions/ChangeCJProductStatus'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ChangeCJProductStatusResponse'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
      security:
        - oAuth2:
            - write
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  TDProduct:
    type: object
    description: TD Product
    properties:
      id:
        type: string
      version:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      productNameCJ:
        type: string
      size:
        type: string
      uom:
        type: string
      brand:
        type: string
      productDescription:
        type: string
      classCode:
        type: string
      className:
        type: string
      oem:
        type: string
      location:
        type: string
      shelfLife:
        type: number
      active:
        type: boolean
      calVat:
        type: boolean
      restricted:
        type: boolean
      barcodes:
        type: array
        items:
          $ref: '#/definitions/TDBarcode'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  TDBarcode:
    type: object
    description: TD Barcode
    properties:
      id:
        type: string
      version:
        type: string
      barcode:
        type: string
      articleNo:
        type: string
      unit:
        type: string
      unitFactor:
        type: number
      barSize:
        type: string
      pkgLength:
        type: number
        format: double
      pkgWidth:
        type: number
        format: double
      pkgHeight:
        type: number
        format: double
      pkgWeight:
        type: number
        format: double
      priceConfigs:
        type: array
        items:
          $ref: '#/definitions/PriceConfig'
      status:
        type: string
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  PriceConfig:
    type: object
    description: PriceConfig
    properties:
      retailPrice:
        type: number
        format: double
      wholesalePrice:
        type: number
        format: double
      effectiveDate:
        type: string
      endDate:
        type: string
  Pagination:
    type: object
    description: Object with paging
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/CJProduct'
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  CJProduct:
    type: object
    description: CJ Product
    properties:
      id:
        type: string
      version:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      classCode:
        type: string
      className:
        type: string
      oem:
        type: string
      source:
        type: string
      supplier:
        type: string
      shelfLife:
        type: integer
      statusTD:
        type: string
      statusCJ:
        type: string
      location:
        type: string
      active:
        type: boolean
      isCalVat:
        type: boolean
      isControlSpecial:
        type: boolean
      cjBarcodes:
        type: array
        items:
          $ref: '#/definitions/CJBarcode'
  CJBarcode:
    type: object
    description: CJ Barcode
    properties:
      id:
        type: string
      version:
        type: string
      barcode:
        type: string
      articleNo:
        type: string
      unit:
        type: string
      unitFactor:
        type: integer
      retailPrice:
        type: number
        format: double
      cost:
        type: number
        format: double
      wholesalePrice:
        type: number
        format: double
      barSize:
        type: string
      pkgLength:
        type: number
        format: double
      pkgWidth:
        type: number
        format: double
      pkgHeight:
        type: number
        format: double
      pkgWeight:
        type: number
        format: double
      active:
        type: boolean
  ChangeCJProductStatus:
    type: object
    description: Change CJ product status
    properties:
      status:
        type: string
      articleNos:
        type: array
        items:
          type: string
  ChangeCJProductStatusResponse:
    type: object
    description: Response of change CJ product status
    properties:
      success:
        type: array
        items:
          type: string
      failure:
        type: array
        items:
          type: string