swagger: '2.0'
info:
  description: TookDee Purchasing API
  version: 1.0.0
  title: Purchasing API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Purchase Request
    description: Purchase Request Profile
schemes:
  - https
  - http
paths:
  '/purchase-requests':
    post:
      tags:
        - Purchase Request
      summary: Create Purchase Request
      operationId: createPurchaseRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Purchase Request
          required: true
          schema:
            $ref: '#/definitions/PurchaseRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseRequest'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - write
    put:
      tags:
        - Purchase Request
      summary: Update Purchase Request Draft
      operationId: updatePurchaseRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Purchase Request
          required: true
          schema:
            $ref: '#/definitions/PurchaseRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseRequest'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - write
    get:
      tags:
        - Purchase Request
      summary: Search Purchase Request
      operationId: findPurchaseRequestsByCriteria
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search by PR number, Requester
          required: false
          type: string
        - name: status
          in: query
          description: Purchase Request status
          required: false
          type: string
        - name: purchaseType
          in: query
          description: Purchase Request Type
          required: false
          type: string
        - name: createdDateFrom
          in: query
          description: Filter created date from (dd/MM/yyyy)
          required: false
          type: string
        - name: createdDateTo
          in: query
          description: Filter created date To (dd/MM/yyyy)
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseRequestPagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found
      security:
        - oAuth2:
            - read
  '/purchase-requests/{id}':
    get:
      tags:
        - Purchase Request
      summary: Get Purchase Request By Id
      operationId: getPurchaseRequestById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: id
          in: path
          description: Purchase Request Id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseRequest'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found
      security:
        - oAuth2:
            - read
    delete:
      tags:
        - Purchase Request
      summary: Delete Purchase Request
      operationId: deletePRById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: id
          in: path
          description: Purchase Request Id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '401':
          description:  >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found

  '/purchase-requests/cancel':
    post:
      tags:
        - Purchase Request
      summary: Cancel Purchase Request
      operationId: cancelPurchaeRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Cancel Reason
          required: true
          schema:
            $ref: '#/definitions/CancelReason'
      responses:
        '200':
          description: successful operation
        '401':
          description:  >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found
  '/purchase-requests/submit':
    post:
      tags:
        - Purchase Request
      summary: Submit Purchase Request
      operationId: submitPurchaseRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Purchase Request
          required: true
          schema:
            $ref: '#/definitions/PurchaseRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseRequest'
        '400':
          description: >
            Validation failure error codes


            > 08009 - Invalid order schedule

            > 08010 - There is an error or change in PR item

            > 08011 - PR item not allow to buy

            > 08012 - PR item invalid article number

            > 08013 - PR item invalid supplier

            > 08014 - PR item invalid unit price

            > 08015 - PR item invalid barcode

            > 08016 - PR item unit price not in cost range

            > 08017 - PR item invalid quantity

          schema:
            $ref: '#/definitions/PurchaseRequestValidationResult'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - write
  '/purchase-requests/approve':
    post:
      tags:
        - Purchase Request
      summary: Approve Purchase Request
      operationId: approvePurchaseRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name:  x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Approve Purchase Request
          required: true
          schema:
            $ref: '#/definitions/ApprovePurchaseRequest'
      responses:
        '200':
          description: successful operation
        '401':
          description:  >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found

  '/purchase-requests/reject':
    post:
      tags:
        - Purchase Request
      summary: Reject Purchase Request
      operationId: rejectPurchaseRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name:  x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Reject Purchase Request
          required: true
          schema:
            $ref: '#/definitions/CancelReason'
      responses:
        '200':
          description: successful operation
        '401':
          description:  >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Purchase Request not found
  '/purchase-product-prices':
    get:
      tags:
        - Purchase Product Price
      summary: Find Purchase Product Prices
      operationId: findPurchaseProductPrices
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "purchase.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search by productName, articleNo, barcode, supplierCode, supplierName
          required: false
          type: string
        - name: purchaseType
          in: query
          description: Purchase Type
          required: false
          type: string
        - name: articleType
          in: query
          description: Article Type "M" or "N"
          required: false
          type: string
        - name: orderingCycle
          in: query
          description: Ordering cycle
          required: false
          type: integer
        - name: pageNo
          in: query
          description: Page Number
          required: false
          type: integer
        - name: pageSize
          in: query
          description: Page Size
          required: false
          type: integer
        - name: sortDirection
          in: query
          description: Sort Direction
          required: false
          type: string
        - name: sortBy
          in: query
          description: Sort By
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PurchaseProductPricePagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  PurchaseRequest:
    type: object
    description: Purchase Request
    properties:
      id:
        type: string
      docNo:
        type: string
      docDate:
        type: string
      orderDate:
        type: string
      type:
        type: string
        enum:
          - Z9
          - Z9-EDIT
          - WAREHOUSE
          - HOTPRICE
          - SUPPLIER
      status:
        type: string
        enum:
          - DRAFT
          - AWAITING_APPROVAL
          - AWAITING_ERP
          - COMPLETED
          - REJECTED
          - CANCELLED
      orderSchedule:
        type: number
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
        description: 1 Monday ... 7 Sunday
      orderScheduleDate:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/PurchaseRequestItem'
      subTotalAmount:
        type: number
        format: double
      vatAmount:
        type: number
        format: double
      totalAmount:
        type: number
        format: double
      version:
        type: number
      createdBy:
        type: string
      createdByName:
        type: string
      lastModifiedBy:
        type: string
      lastModifiedByName:
        type: string
      createdDate:
        type: string
      lastModifiedDate:
        type: string
  PurchaseRequestItem:
    type: object
    description: Purchase Request Item
    properties:
      itemNo:
        type: number
      articleNo:
        type: string
      barcode:
        type: string
      productName:
        type: string
      orderUnit:
        type: string
      minimumOrder:
        type: number
        format: double
      quantity:
        type: number
        format: double
      unitPrice:
        type: number
        format: double
      vatAmount:
        type: number
        format: double
      amount:
        type: number
        format: double
      supplierCode:
        type: string
      supplierName:
        type: string
      selected:
        type: boolean
  PurchaseRequestPagination:
    type: object
    description: Pagination of Purchase Request
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/PurchaseRequestListItem'
  Pagination:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  PurchaseRequestListItem:
    type: object
    description: Purchase Request List Item
    properties:
      id:
        type: string
      prNumber:
        type: string
      type:
        type: string
        enum:
          - Z9
          - Z9_EDIT
          - WAREHOUSE
          - HOTPRICE
          - SUPPLIER
      totalAmount:
        type: number
      requester:
        type: string
      createdDate:
        type: string
      status:
        type: string
        enum:
          - DRAFT
          - AWAITING_APPROVAL
          - AWAITING_ERP
          - COMPLETED
          - REJECTED
          - CANCELLED
      advance:
        type: boolean
      orderSchedule:
        type: string
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
  CancelReason:
    type: object
    description: Cancel reason
    properties:
      id:
        type: string
      reason:
        type: string
  PurchaseRequestItemValidationError:
    type: object
    properties:
      field:
        type: string
      code:
        type: string
      message:
        type: string
  PurchaseRequestItemChange:
    type: object
    properties:
      field:
        type: string
      before:
        type: object
      after:
        type: object
  PurchaseRequestItemValidationResult:
    type: object
    properties:
      itemNo:
        type: integer
      changes:
        type: array
        items:
          $ref: '#/definitions/PurchaseRequestItemChange'
      errors:
        type: array
        items:
          $ref: '#/definitions/PurchaseRequestItemValidationError'
  PurchaseRequestValidationResult:
    type: object
    description: Submit Purchase Request Error Response
    properties:
      code:
        type: string
      message:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/PurchaseRequestItemValidationResult'
  ApprovePurchaseRequest:
    type: object
    description: Approve Purchase Request
    properties:
      id:
        type: string
      comment:
        type: string
      approvedPrItem:
        type: array
        items:
          type: string
      subTotalAmount:
        type: number
      varAmount:
        type: number
      totalAmount:
        type: number
  PurchaseProductPricePagination:
    type: object
    description: Pagination of Purchase Product Price
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/PurchaseProductPrice'
  PurchaseProductPrice:
    type: object
    description: Purchase Product Price
    properties:
      articleNo:
        type: string
      barcode:
        type: string
      productName:
        type: string
      productStatus:
        type: string
      supplierCode:
        type: string
      supplierName:
        type: string
      orderUnit:
        type: string
      orderBaseUnitFactor:
        type: integer
      pickingUnitFactor:
        type: integer
      minimumOrder:
        type: number
        format: double
      unitPrice:
        type: number
        format: double
      vatAmount:
        type: number
        format: double
      vatPct:
        type: number
        format: double