swagger: '2.0'
info:
  description: This is the Salesforce connect API
  version: 1.0.0
  title: Salesforce connect API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
schemes:
  - https
  - http
paths:
  /campaigns:
    get:
      tags:
        - Campaigns
      summary: Get campaign list
      operationId: getCampaigns
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CampaignsResponse'
        '404':
          description: Campaign not found
      security:
        - oAuth2:
            - read
  /provinces:
    get:
      tags:
        - Master data
      summary: Get province list
      operationId: getProvinces
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ProvincesResponse'
        '404':
          description: Province not found
      security:
        - oAuth2:
            - read
  /districts:
    get:
      tags:
        - Master data
      summary: Get district list
      operationId: getDistricts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: districtId
          in: query
          description: Query param filter by districtId "?districtId=a011y000000mTTmAAM"
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DistrictsResponse'
        '404':
          description: District not found
      security:
        - oAuth2:
            - read
  /subDistricts:
    get:
      tags:
        - Master data
      summary: Get subDistrict list
      operationId: getSubDistricts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: postalCode
          in: query
          description: Query param filter postalCode "?postalCode=10200"
          required: false
          type: string   
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SubDistrictsResponse'
        '404':
          description: SubDistrict not found
      security:
        - oAuth2:
            - read           
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:      
  CampaignsResponse:
    type: array
    description: List of campaign
    items:
      $ref: '#/definitions/CampaignResponse'
  CampaignResponse:
    type: object
    description: Object of campaign
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      status:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      active:
        type: boolean
      bannerHeaderUrl:
        type: string
      code:
         type: string   
      maximumAttendance:
         type: string  
      childCampaigns:
        type: array
        items:
          $ref: '#/definitions/ChildCampaignResponse'
  ChildCampaignResponse:
    type: object
    description: Object of round child campaign
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string  
      status:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      bannerSuccessUrl:
        type: string
      bannerFailedUrl:
        type: string     
      rounds:
        type: array
        items:
          $ref: '#/definitions/RoundCampaignResponse'
  RoundCampaignResponse:
    type: object
    description: Object of round campaign
    properties:
      id:
        type: string
      name:
        type: string
      status:
        type: string
      active:
        type: boolean
      numberSent:
        type: number
      expectedResponse:
        type: number
      respondedCount:
        type: number
  ProvincesResponse:
    type: array
    description: List of province
    items:
      $ref: '#/definitions/ProvinceResponse'
  ProvinceResponse:
    type: object
    description: Object of province
    properties:
      provinceId:
        type: string  
      provinceName:
        type: string
  DistrictsResponse:
    type: array
    description: List of district
    items:
      $ref: '#/definitions/DistrictResponse'
  DistrictResponse:
    type: object
    description: Object of district
    properties:
      districtId:
        type: string
      districtName:
        type: string  
      provinceId:
        type: string  
      provinceName:
        type: string
  SubDistrictsResponse:
    type: array
    description: List of subDistrict
    items:
      $ref: '#/definitions/SubDistrictResponse'
  SubDistrictResponse:
    type: object
    description: Object of subDistrict
    properties:
      subDistrictId:
        type: string
      subDistrictName:
        type: string
      districtId:
        type: string   
      postalCode:
        type: string