swagger: '2.0'
info:
  description: This is the stock API
  version: 1.0.0
  title: Stock API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
schemes:
  - https
  - http
paths:
  /stocks/{location}/{articleNo}:
    get:
      tags:
        - Stock Profile
      summary: Get stock by location and article no
      operationId: findStockByLocationAndArticleNo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "stock.api.tdshop.io"
          required: true
          type: string
        - name: location
          in: path
          description: Location Id
          required: true
          type: string
        - name: articleNo
          in: path
          description: Article no
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StockDto'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Stock not found
      security:
        - oAuth2:
            - read

  /stocks/{location}/{articleNo}/movement:
    get:
      tags:
        - Stock Profile
      summary: Get stock movement
      operationId: findStockMovementByLocationAndArticleNo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "stock.api.tdshop.io"
          required: true
          type: string
        - name: location
          in: path
          description: Location Id
          required: true
          type: string
        - name: articleNo
          in: path
          description: Article no
          required: true
          type: string
        - name: movementDateFrom
          in: query
          description: Filter movement date from (dd/MM/yyyy)
          required: false
          type: string
        - name: movementDateTo
          in: query
          description: Filter movement date to (dd/MM/yyyy)
          required: false
          type: string
        - name: page
          in: query
          description: Number of page (Default 0)
          required: false
          type: integer
        - name: size
          in: query
          description: Size per page (Default 20)
          required: false
          type: integer
        - name: sortOrder
          in: query
          description: asc or desc
          required: false
          type: string
        - name: sortBy
          in: query
          description: 'Field name eg. lastModifiedDate'
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StockMovementPagination'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read

  /stocks:
    get:
      tags:
        - Stock Profile
      summary: Get stock by criterias
      operationId: findStockByCriteria
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "stock.api.tdshop.io"
          required: true
          type: string
        - name: warehouse
          in: query
          description: >-
            Use warehouse code
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: >-
            Search criteria on "Product Name" or "Article No."
          required: false
          type: string
        - name: productStatus
          in: query
          description: >-
            Product status SELECT, NEW, ACTIVE, SEASONAL, HOLD_BUY, RECALL,
            CLEAR, CLEAR_PROMOTION, HOLD_BUY_SELL, OUT_OF_STOCK, DELETE
          required: false
          type: string
        - name: segment
          in: query
          description: >-
            Use segment code
          required: false
          type: string
        - name: family
          in: query
          description: >-
            Use family code
          required: false
          type: string
        - name: classCode
          in: query
          description: >-
            Use class code
          required: false
          type: string
        - name: subClass
          in: query
          description: >-
            Use subclass code
          required: false
          type: string
        - name: productType
          in: query
          description: >-
            Product Type INVENTORY, FIX_ASSET, STORE_USE
          required: false
          type: string
        - name: lastUpdatedDateFrom
          in: query
          description: >-
            Filter greater than or equal lastModifiedDate (dd/MM/yyyy)
          required: false
          type: string
        - name: lastUpdatedDateTo
          in: query
          description: >-
            Filter less than or equal lastModifiedDate (dd/MM/yyyy)
          required: false
          type: string
        - name: page
          in: query
          description: No. of page
          required: false
          type: integer
        - name: size
          in: query
          description: No. of records
          required: false
          type: integer
        - name: sortOrder
          in: query
          description: Ascending (asc) or Deascending (desc)
          required: false
          type: string
        - name: sortBy
          in: query
          description: Properties name
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StockListDto'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Stock not found
      security:
        - oAuth2:
            - read

  /stocks/adjust:
    get:
      tags:
        - Stock Profile
      summary: Get stock adjust by criterias
      operationId: findStockAdjustByCriteria
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "stock.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: >-
            Search criteria on "Request No" or "Location Code" or "Location Name" or "Requested By" or "Created By"
          required: false
          type: string
        - name: status
          in: query
          description: >-
            WAREHOUSE, STORE
          required: false
          type: string
        - name: createdDateFrom
          in: query
          description: >-
            Filter greater than or equal lastModifiedDate (dd/MM/yyyy)
          required: false
          type: string
        - name: createdDateTo
          in: query
          description: >-
            Filter less than or equal lastModifiedDate (dd/MM/yyyy)
          required: false
          type: string
        - name: page
          in: query
          description: No. of page
          required: false
          type: integer
        - name: size
          in: query
          description: No. of records
          required: false
          type: integer
        - name: sortOrder
          in: query
          description: Ascending (asc) or Deascending (desc)
          required: false
          type: string
        - name: sortBy
          in: query
          description: Properties name
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StockAdjustListDto'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Stock not found
      security:
        - oAuth2:
            - read

  /stocks/adjust/{docNo}:
    get:
      tags:
        - Stock Profile
      summary: Get stock adjust by criterias
      operationId: findStockAdjust
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "marketing.api.tdshop.io"
          required: true
          type: string
        - name: docNo
          in: path
          description: Stock adjust document no
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StockAdjustDto'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Stock not found
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  StockDto:
    type: object
    description: Object for Stock
    properties:
      id:
        type: string
      location:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      productStatus:
        type: string
      stockDetail:
        $ref: '#/definitions/StockDetailDto'
      quantity:
        type: integer
  StockDetailDto:
    type: object
    description: Object for Stock Detail
    properties:
      warehouse:
        type: integer
      reserved:
        type: integer
      inTransit:
        type: integer
      store:
        type: integer
      toBeAdjusted:
        type: integer
  StockMovementDto:
    type: object
    description: Object for Stock Movement
    properties:
      id:
        type: string
      refNo:
        type: string
      location:
        type: string
      movementType:
        type: string
      stockMovementDetail:
        $ref: '#/definitions/StockMovementDetailDto'
      createdBy:
        type: string
  StockMovementDetailDto:
    type: object
    description: Object for Stock Movement Detail
    properties:
      warehouse:
        type: integer
      store:
        type: integer
      adjust:
        type: integer
      existingStock:
        type: integer
  StockListDto:
    type: object
    description: Object for display at stock list
    properties:
      id:
        type: string
      totalStock:
        type: integer
      articleNo:
        type: string
      productName:
        type: string
      segmentName:
        type: string
      familyName:
        type: string
      className:
        type: string
      subClassName:
        type: string
      deliveryMethod:
        type: string
      lastUpdated:
        type: string
      productStatus:
        $ref: '#/definitions/ProductStatus'
      productType:
        $ref: '#/definitions/ProductType'
      productImage:
        $ref: '#/definitions/ProductImageDto'
  ProductImageDto:
    type: object
    description: Object of Product Image when return to client
    properties:
      id:
        type: string
      smallSizeFilePath:
        type: string
      mediumSizeFilePath:
        type: string
      fileName:
        type: string
      directory:
        type: string
  StockAdjustListDto:
    type: object
    description: Object of stock adjust list when return to client
    properties:
      id:
        type: string
      requestNo:
        type: string
      locationCode:
        type: string
      locationName:
        type: string
      requester:
        type: string
      status:
        $ref: '#/definitions/StockAdjustStatus'
      locationType:
        $ref: '#/definitions/LocationType'
      requestedDate:
        type: string
        format: date
      createdDate:
        type: string
        format: date
  StockAdjustDto:
    type: object
    description: Object of stock adjust when return to client
    properties:
      id:
        type: string
      version:
        type: integer
      docNo:
        type: string
      location:
        type: string
      items:
        $ref: '#/definitions/AdjustItemDto'
      locationType:
        $ref: '#/definitions/LocationType'
      requester:
        type: string
      status:
        $ref: '#/definitions/StockAdjustStatus'
      requestedDate:
        type: string
        format: date
      createdDate:
        type: string
        format: date
      createdBy:
        type: string
      createdByName:
        type: string
      lastModifiedBy:
        type: string
      lastModifiedByName:
        type: string
      lastModifiedDate:
        type: string
        format: date
  AdjustItemDto:
    type: object
    description: Object for Stock Item
    properties:
      articleNo:
        type: string
      productName:
        type: string
      adjustStock:
        type: integer
      reason:
        type: string
      unit:
        type: string
      unitFactor:
        type: integer
  ProductStatus:
    type: string
    enum:
      - SELECT
      - NEW
      - ACTIVE
      - SEASONAL
      - HOLD_BUY
      - RECALL
      - CLEAR
      - CLEAR_PROMOTION
      - HOLD_BUY_SELL
      - OUT_OF_STOCK
      - DELETE
  DeliveryMethod:
    type: string
    enum:
      - TD
      - SUPPLIER
  ProductType:
    type: string
    enum:
      - INVENTORY
      - FIX_ASSET
      - STORE_USE
  LocationType:
    type: string
    enum:
      - WAREHOUSE
      - STORE
  StockAdjustStatus:
    type: string
    enum:
      - NEW
      - COMPLETED
      - FAILED
  Pagination:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  StockMovementPagination:
    type: object
    description: Pagination object for Voucher Requests
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/StockMovementDto'