swagger: '2.0'
info:
  description: This is the store API
  version: 1.0.0
  title: Store API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Store Profile
    description: Store Profile
schemes:
  - https
  - http
paths:
  '/stores/{storeId}':
    get:
      tags:
        - Store Profile
      summary: Get store profile
      operationId: findById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "store.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: storeId
          in: path
          description: Store id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Store'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - read
  '/stores  ':
    get:
      tags:
        - Store Profile
      summary: Get store list by cretiria
      operationId: findStores
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "store.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: merchantId
          in: query
          description: Merchant Id
          required: false
          type: string
        - name: storeCountryId
          in: query
          description: Store country Id
          required: false
          type: string
        - name: storeGroupId
          in: query
          description: Store group Id
          required: false
          type: string
        - name: searchCriteria
          in: query
          description: search criteria which query from storeCode and storeName
          required: false
          type: string
        - name: active
          in: query
          description: store active status
          required: false
          type: boolean
        - name: page
          in: query
          description: Page number
          required: false
          type: integer
        - name: size
          in: query
          description: number record per one page
          required: false
          type: integer   
        - name: sortBy
          in: query
          description: field name for sorting
          required: false
          type: string
        - name: sortOrder
          in: query
          description: sorting direction ('desc','asc')
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StoreList'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  '/stores':
    post:
      tags:
        - Store Profile
      summary: Create a new store profile
      operationId: createStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "store.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: New store payload
          required: true
          schema:
            $ref: '#/definitions/Store'
      responses:
        '201':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
  '/stores ':
    put:
      tags:
        - Store Profile
      summary: Update store profile
      operationId: updateStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "store.api.tdshop.io"
          required: true
          type: string
        - name: x-tenant-id
          in: header
          description: Custom tenant id as "\*:\*:\*:\*"
          required: true
          type: string
        - name: x-user-id
          in: header
          description: user id
          required: true
          type: string
        - name: body
          in: body
          description: Update store payload
          required: true
          schema:
            $ref: '#/definitions/Store'
      responses:
        '200':
          description: successful operation
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error 
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: Store not found
      security:
        - oAuth2:
            - write
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  StoreList:
    type: object
    description: Store
    properties:
      id:
        type: string
      merchant:
        type: string
      storeCountry:
        type: string
      storeGroup:
        type: string
      store:
        $ref: '#/definitions/StoreDetail'
  StoreDetail:
    type: object
    description: Store detail
    properties:
      id:
        type: string
      merchant:
        type: string
      storeCountry:
        type: string
      storeGroup:
        type: string
      code:
        type: string
      name:
        type: string
      active:
        type: boolean
      delete:
        type: boolean
      createdDate:
        type: string
      lastModifiedDate:
        type: string
  Store:
    type: object
    description: Store
    properties:
      id:
        type: string
      version:
        type: string
      merchant:
        type: string
      storeCountry:
        type: string
      storeGroup:
        type: string
      groupHierarchy:
        type: array
        items:
          type: string
      code:
        type: string
      name:
        type: string
      active:
        type: boolean
      delete:
        type: boolean
      contact:
        $ref: '#/definitions/Contact'
      receipt:
        $ref: '#/definitions/Receipt'
      policy:
        $ref: '#/definitions/Policy'
      devices:
        type: array
        items:
          $ref: '#/definitions/Device'
      createdDate:
        type: string
      createdBy:
        type: string
      lastModifiedDate:
        type: string
      lastModifiedBy:
        type: string
  Contact:
    type: object
    description: Contact
    properties:
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
  Receipt:
    type: object
    description: Receipt
    required:
      - address
    
    properties:
      header:
        type: string
      address:
        type: string
      taxId:
        type: string
      branchNo:
        type: string
      footer:
        type: string
  
  Policy:
    type: object
    description: Policy
    properties:
      minOrder: 
        $ref: '#/definitions/Money'
      orderSchedule:
        type: array
        items:
          type: string
      deliverySchedule:
        type: array
        items:
          type: string
      currency:
        type: string
      language:
        type: string
      timezone:
        type: string
      country:
        type: string
      openTime:
        type: string
      closeTime:
        type: string
  Device:
    type: object
    description: Device
    properties:
      code:
        type: string
      type:
        type: string
      reference1:
        type: string
      reference2:
        type: string
      reference3:
        type: string
  Money:
    type: object
    description: Money type
    properties:
      amount:
        type: number
      currency:
        type: string