swagger: '2.0'
info:
  description: This is the warehouse API
  version: 1.0.0
  title: Warehouse API
  termsOfService: 'https://api.tdshop.io/'
basePath: /
tags:
  - name: Delivery Order
    description: Delivery Order Profile
schemes:
  - https
  - http
paths:
  '/delivery-orders':
    get:
      tags:
        - Delivery Order
      summary: Search delivery orders
      operationId: fetchDeliveryOrders
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search by deliver order no., order no., store code, store name, delivery by, plate no., driver
          required: false
          type: string
        - name: status
          in: query
          description: Delivery order status
          required: false
          type: string
        - name: createdDateFrom
          in: query
          description: Filter created date from (dd/MM/yyyy)
          required: false
          type: string
        - name: createdDateTo
          in: query
          description: Filter created date to (dd/MM/yyyy)
          required: false
          type: string
        - name: requestedDeliveryDateFrom
          in: query
          description: Filter requested delivery date from (dd/MM/yyyy)
          required: false
          type: string
        - name: requestedDeliveryDateTo
          in: query
          description: Filter requested delivery date to (dd/MM/yyyy)
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/DeliveryOrderPagination'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
  '/delivery-orders/{id}':
    get:
      tags:
        - Delivery Order
      summary: Get delivery order
      operationId: findDeliveryOrderById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: id
          in: path
          description: Delivery order id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DeliveryOrder'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error
        '404':
          description: Delivery order not found
      security:
        - oAuth2:
            - write
  '/delivery-orders/{id}/split/draft':
    post:
      tags:
        - Delivery Order
      summary: Split draft delivery order
      operationId: splitDraftDeliveryOrder
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Delivery order
          required: true
          schema:
            $ref: '#/definitions/SplitDeliveryOrder'
        - name: id
          in: path
          description: Delivery order id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - write
  '/delivery-orders/{id}/split/submit':
    post:
      tags:
        - Delivery Order
      summary: Submit split delivery order
      operationId: submitSplitDeliveryOrder
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Delivery order
          required: true
          schema:
            $ref: '#/definitions/SplitDeliveryOrder'
        - name: id
          in: path
          description: Delivery order id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - write
  '/delivery-orders/export-picking':
    post:
      tags:
        - Delivery Order
      summary: Export delivery order for picking
      operationId: exportPickingDeliveryOrder
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: requestedDeliveryDateFrom
          in: query
          description: Filter greater than or equal requested delivery date from (dd/MM/yyyy)
          required: false
          type: string
        - name: requestedDeliveryDateTo
          in: query
          description: Filter less than or equal requested delivery date to (dd/MM/yyyy)
          required: false
          type: string
        - name: 'status[]'
          in: query
          description: 'Filter status NEW,PICKING,PICKED'
          required: false
          type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '404':
          description: >
            There is no delivery order items to be exported for picking
        '400':
          description: >
            05004 - delivery order item result limited exceed (50,000)
      security:
        - oAuth2:
            - read
  '/shipments':
    post:
      tags:
        - Shipment
      summary: Create Shipment
      operationId: createShipment
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: body
          in: body
          description: Shipment
          required: true
          schema:
            $ref: '#/definitions/CreateShipmentRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/Shipment'
          description: successful operation
        '401':
          description: >
            Not authorized, refer to www-authenticate header to describe an
            error

            Example: Bearer error="invalid_token", error_description="Jwt
            expired at 2019-02-12T12:00:04Z",
            error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
        '400':
          description: >

      security:
        - oAuth2:
            - write
    get:
      tags:
        - Shipment
      summary: Search shipment
      operationId: fetchShipments
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-host
          in: header
          description: Custom host header as "warehouse.api.tdshop.io"
          required: true
          type: string
        - name: searchCriteria
          in: query
          description: Search by delivery by, plate no., driver, created by
          required: false
          type: string
        - name: status
          in: query
          description: Shipment status
          required: false
          type: string
        - name: deliveryDateFrom
          in: query
          description: Filter delivery date from (dd/MM/yyyy)
          required: false
          type: string
        - name: deliveryDateTo
          in: query
          description: Filter delivery date to (dd/MM/yyyy)
          required: false
          type: string
        - name: pickupDateFrom
          in: query
          description: Filter pickup date from (dd/MM/yyyy)
          required: false
          type: string
        - name: pickupDateTo
          in: query
          description: Filter pickup date to (dd/MM/yyyy)
          required: false
          type: string
        - name: createdDateFrom
          in: query
          description: Filter created date from (dd/MM/yyyy)
          required: false
          type: string
        - name: createdDateTo
          in: query
          description: Filter created date to (dd/MM/yyyy)
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ShipmentPagination'
        '401':
          description: |
            Not authorized, refer to www-authenticate header to describe an error
            Example: Bearer error="invalid_token", error_description="Jwt expired at 2019-02-12T12:00:04Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
      security:
        - oAuth2:
            - read
securityDefinitions:
  oAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.tdshop.io'
    tokenUrl: 'https://api.tdshop.io/auth/token'
    scopes:
      read: Grants read access
      write: Grants write access
definitions:
  Pagination:
    type: object
    description: Object with paging
    properties:
      page:
        type: integer
      size:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      numberOfElements:
        type: integer
      totalPages:
        type: integer
      hasContent:
        type: boolean
      last:
        type: boolean
      empty:
        type: boolean
  StoreType:
    type: string
    enum:
      - STORE_MODEL
      - EARLIER_PARTNER
      - PARTNER_MODEL
  OrderType:
    type: string
    enum:
      - NORMAL
  DeliveryOrderStatus:
    type: string
    enum:
      - DRAFT
      - NEW
      - PICKING
      - PICKED
      - LOADED
      - DISPATCHED
      - DELIVERED
      - CLOSED
      - COMPLETED
  Contact:
    type: object
    description: Contact
    properties:
      address:
        type: string
      state:
        type: string
      postCode:
        type: string
      country:
        type: string
      countryCode:
        type: string
      mobileNo:
        type: string
  Response:
    type: object
    description: Response payload
    properties:
      message:
        type: string
  DeliveryOrderItem:
    type: object
    description: Delivery Order Item
    properties:
      splitNo:
        type: integer
      itemNo:
        type: integer
      productName:
        type: string
      articleNo:
        type: string
      barcode:
        type: string
      unit:
        type: string
      qty:
        type: integer
      assignedQty:
        type: integer
      pickedQty:
        type: integer
  SplitDeliveryOrderItem:
    type: object
    description: Split delivery order item
    properties:
      itemNo:
        type: integer
      splitNo:
        type: integer
  SplitDeliveryOrder:
    type: object
    description: Split delivery order request payload
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/SplitDeliveryOrderItem'
  DeliveryOrder:
    type: object
    description: Delivery Order
    properties:
      id:
        type: string
      doNo:
        type: string
      doStatus:
        $ref: '#/definitions/DeliveryOrderStatus'
      poNo:
        type: string
      storeCode:
        type: string
      storeName:
        type: string
      storeType:
        $ref: '#/definitions/StoreType'
      orderType:
        $ref: '#/definitions/OrderType'
      shipTo:
        $ref: '#/definitions/Contact'
      deliveryByFourWheelsTruck:
        type: boolean
      noEntry:
        type: string
      deliveryNote:
        type: string
      requestedDeliveryDate:
        type: string
      createdDate:
        type: string
      lastModifiedDate:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/DeliveryOrderItem'
  DeliveryOrderListItem:
    type: object
    description: Delivery Order List Item
    properties:
      id:
        type: string
      doNo:
        type: string
      poNo:
        type: string
      storeCode:
        type: string
      storeName:
        type: string
      requestedDeliveryDate:
        type: string
      createdDate:
        type: string
      lastModifiedDate:
        type: string
      doStatus:
        $ref: '#/definitions/DeliveryOrderStatus'
  DeliveryOrderPagination:
    type: object
    description: Pagination object for Delivery Orders
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/DeliveryOrderListItem'
  CreateShipmentRequest:
    type: object
    description: Create shipment request
    properties:
      courierCode:
        type: string
      courierName:
        type: string
      shipCharge:
        type: number
        format: double
      plateNo:
        type: string
      driverName:
        type: string
      deliveryDate:
        type: string
      pickupDate:
        type: string
      deliveryOrders:
        type: array
        items:
          type: string
  ShipmentStatus:
    type: string
    enum:
      - AWAITING
      - DISPATCHED
      - DELIVERED
      - COMPLETED
  Shipment:
    type: object
    description: Shipment
    properties:
      id:
        type: string
      shipmentNo:
        type: string
      status:
        $ref: '#/definitions/ShipmentStatus'
      courierCode:
        type: string
      courierName:
        type: string
      shipCharge:
        type: number
        format: double
      plateNo:
        type: string
      driverName:
        type: string
      deliveryDate:
        type: string
      pickupDate:
        type: string
      createdDate:
        type: string
      createdBy:
        type: string
  ShipmentListItem:
    type: object
    description: Delivery Order List Item
    properties:
      id:
        type: string
      shipmentNo:
        type: string
      status:
        $ref: '#/definitions/ShipmentStatus'
      courierCode:
        type: string
      courierName:
        type: string
      shipCharge:
        type: number
        format: double
      plateNo:
        type: string
      driverName:
        type: string
      deliveryDate:
        type: string
      pickupDate:
        type: string
      createdDate:
        type: string
      createdBy:
        type: string
  ShipmentPagination:
    type: object
    description: Pagination object for Shipment
    allOf:
      - $ref: '#/definitions/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/ShipmentListItem'