ProductSnapshotDto:
    type: object
    properties:
      tdProductSnapshot:
        type: object
        $ref: './ProductDto.yaml#/ProductDto'
      cjProductSnapshot:
        type: object
        $ref: './CJProductDto.yaml#/CJProductDto'
      barcodeSnapshots:
        type: array
        items:
          $ref: './BarcodeSnapshotDto.yaml#/BarcodeSnapshotDto'
      wholesaleSettingSnapshots:
        type: array
        items:
          $ref: './WholesaleSettingSnapshotDto.yaml#/WholesaleSettingSnapshotDto'
      supplierPriceSnapshots:
        type: array
        items:
          $ref: './SupplierPriceSnapshotDto.yaml#/SupplierPriceSnapshotDto'
      changeProducts:
        type: array
        items:
          $ref: './Change.yaml#/Change'