ProductImageDto:
    type: object
    description: Object of Product Image when return to client
    properties:
      id:
        type: string
      original:
        type: string
      small:
        type: string
      medium:
        type: string
      fileName:
        type: string
      directory:
        type: string