ProductStackPriceDto:
    type: object
    description: Object to display in product price stack page
    properties:
      id:
        type: string
      articleNo:
        type: string
      productName:
        type: string
      className:
        type: string
      wholesalePrice:
        type: number
        format: double
      unit:
        type: string
      productStatus:
        type: string
      schedule:
        type: boolean
ProductStackPriceDtoPagination:
    type: object
    description: Pagination object for ProductStackPriceDto
    allOf:
      - $ref: './Pagination.yaml#/Pagination'
      - type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/ProductStackPriceDto'