StackPriceConfigDto:
    type: object
    description: Object will send when has a update from manage stack pricing
    properties:
      wholesalePrices:
        type: array
        items:
          $ref: './WholesalePriceDto.yaml#/WholesalePriceDto'
      manageStackPricings:
        type: array
        items:
          $ref: './WholesalePriceDto.yaml#/WholesalePriceDto'