TDSearchPriceConfig:
    type: object
    description: Price object when search from elastic
    properties:
      createdDate:
        type: string
        format: date
      createdBy:
        type: string
      lastModifiedDate:
        type: string
        format: date
      lastModifiedBy:
        type: string
      articleNo:
        type: string
      barcode:
        type: string
      configType:
        type: string
        enum: [WHOLESALE,RETAIL]
      price:
        type: object
        $ref: './MonetaryAmount.yaml#/MonetaryAmount'
      active:
        type: boolean
      effectiveDate:
        type: string
        format: date